SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `Departures` (
  `ID` int(11) NOT NULL,
  `LineID` int(11) NOT NULL,
  `Time` time NOT NULL,
  `WeekDay` int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `Line` (
  `ID` int(11) NOT NULL,
  `ValidTo` date NOT NULL,
  `Name` varchar(50) NOT NULL,
  `Zone` varchar(10) NOT NULL,
  `FirstStopID` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `LineStop` (
  `ID` int(11) NOT NULL,
  `StopID` int(11) NOT NULL,
  `LineID` int(11) NOT NULL,
  `NextLineStopID` int(11) DEFAULT NULL,
  `TimeToNextStop` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `Stop` (
  `ID` int(11) NOT NULL,
  `Name` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


ALTER TABLE `Departures`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `DeparturesLineID_to_LineID` (`LineID`);

ALTER TABLE `Line`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `LineFirstStopID_to_StopID` (`FirstStopID`);

ALTER TABLE `LineStop`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `LineStopLineID_To_LineID` (`LineID`),
  ADD KEY `LineStopStopID_To_StopID` (`StopID`),
  ADD KEY `LineStopNextStopID_To_LineStopID` (`NextLineStopID`);

ALTER TABLE `Stop`
  ADD PRIMARY KEY (`ID`);


ALTER TABLE `Departures`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `Line`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `LineStop`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `Stop`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT;


ALTER TABLE `Departures`
  ADD CONSTRAINT `DeparturesLineID_to_LineID` FOREIGN KEY (`LineID`) REFERENCES `Line` (`ID`) ON DELETE CASCADE;

ALTER TABLE `Line`
  ADD CONSTRAINT `LineFirstStopID_to_StopID` FOREIGN KEY (`FirstStopID`) REFERENCES `LineStop` (`ID`) ON DELETE CASCADE;

ALTER TABLE `LineStop`
  ADD CONSTRAINT `LineStopLineID_To_LineID` FOREIGN KEY (`LineID`) REFERENCES `Line` (`ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `LineStopNextStopID_To_LineStopID` FOREIGN KEY (`NextLineStopID`) REFERENCES `LineStop` (`ID`),
  ADD CONSTRAINT `LineStopStopID_To_StopID` FOREIGN KEY (`StopID`) REFERENCES `Stop` (`ID`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
